### ISSUE TITLE
Version de Bootstrap 

### ISSUE THREAD

**Issue by jeremy-p** [Maxouwell/chatlite#4]
Pourquoi utiliser la version 3.3.5 de Bootstrap ?
La dernière stable est la 3.3.7, et il serait peut-être plus pratique d'utiliser un CDN, non ?

En plus ça permettrait d'utiliser les Glyphicons sans avoir à ajouter de nouveaux fichiers (car les fonts ne sont pas dans le projet actuellement).

**Comment by Maxouwell** [comment]
Parce que la version embarqué par Spring boot est la 3.3.5 :)

**Comment by Maxouwell** [comment]
#5 Duplicate
