### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by jeremy-p** [Maxouwell/chatlite#5]
Voici ma proposition d'interface, ça ne révolutionne rien, mais c'est plus clair et adapté aux mobiles (au passage, je vire le tableau qui n'avait rien à faire là)
Au passage j'ai utilisé le CDN de Bootstrap.

## PCMASTERRACE
![pc](https://user-images.githubusercontent.com/30982183/29328937-817809fc-81f4-11e7-829e-9be22614a074.png)

## Mobile
![mobile](https://user-images.githubusercontent.com/30982183/29328946-89b073f2-81f4-11e7-9c70-a9c959ec6e90.png)

### CSS ajouté
`.date {
  font-style: 90%;
  font-family: monospace,monospace;
}`

### HTML

[Chat lite.zip](https://github.com/Maxouwell/chatlite/files/1225917/Chat.lite.zip)

**Comment by Maxouwell** [comment]
Mis à jour avec le commit 
https://github.com/Maxouwell/chatlite/commit/517234c19d1b7247662563bafa5a4d10b5235d53
